package com.froad.beans;

// Generated 2014-2-18 16:27:25 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Rckcluster generated by hbm2java
 */
@Entity
@Table(name = "RCKCLUSTER")
public class Rckcluster implements java.io.Serializable {

    private String clustertype;
    private String hostaddr;
    private String exestate;
    private String exedate;
    private String exestarttime;
    private String exeendtime;
    private String isexecute;
    private String isassign;
    private String assignhostaddr;
    private String remark;

    public Rckcluster() {
    }

    public Rckcluster(String clustertype) {
        this.clustertype = clustertype;
    }

    public Rckcluster(String clustertype, String hostaddr, String exestate,
                      String exedate, String exestarttime, String exeendtime,
                      String isexecute, String isassign, String assignhostaddr,
                      String remark) {
        this.clustertype = clustertype;
        this.hostaddr = hostaddr;
        this.exestate = exestate;
        this.exedate = exedate;
        this.exestarttime = exestarttime;
        this.exeendtime = exeendtime;
        this.isexecute = isexecute;
        this.isassign = isassign;
        this.assignhostaddr = assignhostaddr;
        this.remark = remark;
    }

    @Id
    @Column(name = "CLUSTERTYPE", unique = true, nullable = false, length = 20)
    public String getClustertype() {
        return this.clustertype;
    }

    public void setClustertype(String clustertype) {
        this.clustertype = clustertype;
    }

    @Column(name = "HOSTADDR")
    public String getHostaddr() {
        return this.hostaddr;
    }

    public void setHostaddr(String hostaddr) {
        this.hostaddr = hostaddr;
    }

    @Column(name = "EXESTATE", length = 5)
    public String getExestate() {
        return this.exestate;
    }

    public void setExestate(String exestate) {
        this.exestate = exestate;
    }

    @Column(name = "EXEDATE", length = 8)
    public String getExedate() {
        return this.exedate;
    }

    public void setExedate(String exedate) {
        this.exedate = exedate;
    }

    @Column(name = "EXESTARTTIME", length = 6)
    public String getExestarttime() {
        return this.exestarttime;
    }

    public void setExestarttime(String exestarttime) {
        this.exestarttime = exestarttime;
    }

    @Column(name = "EXEENDTIME", length = 6)
    public String getExeendtime() {
        return this.exeendtime;
    }

    public void setExeendtime(String exeendtime) {
        this.exeendtime = exeendtime;
    }

    @Column(name = "ISEXECUTE", length = 1)
    public String getIsexecute() {
        return this.isexecute;
    }

    public void setIsexecute(String isexecute) {
        this.isexecute = isexecute;
    }

    @Column(name = "ISASSIGN", length = 1)
    public String getIsassign() {
        return this.isassign;
    }

    public void setIsassign(String isassign) {
        this.isassign = isassign;
    }

    @Column(name = "ASSIGNHOSTADDR")
    public String getAssignhostaddr() {
        return this.assignhostaddr;
    }

    public void setAssignhostaddr(String assignhostaddr) {
        this.assignhostaddr = assignhostaddr;
    }

    @Column(name = "REMARK")
    public String getRemark() {
        return this.remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

}
