package com.froad.beans;

// Generated 2013-11-5 11:49:49 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RckflowdetailId generated by hbm2java
 */
@Embeddable
public class RckflowdetailId implements java.io.Serializable {

    private String cleardate;
    private String rcktype;
    private int rckorder;

    public RckflowdetailId() {
    }

    public RckflowdetailId(String cleardate, String rcktype, int rckorder) {
        this.cleardate = cleardate;
        this.rcktype = rcktype;
        this.rckorder = rckorder;
    }

    @Column(name = "CLEARDATE", nullable = false, length = 16)
    public String getCleardate() {
        return this.cleardate;
    }

    public void setCleardate(String cleardate) {
        this.cleardate = cleardate;
    }

    @Column(name = "RCKTYPE", nullable = false, length = 20)
    public String getRcktype() {
        return this.rcktype;
    }

    public void setRcktype(String rcktype) {
        this.rcktype = rcktype;
    }

    @Column(name = "RCKORDER", nullable = false, precision = 9, scale = 0)
    public int getRckorder() {
        return this.rckorder;
    }

    public void setRckorder(int rckorder) {
        this.rckorder = rckorder;
    }

    public boolean equals(Object other) {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof RckflowdetailId))
            return false;
        RckflowdetailId castOther = (RckflowdetailId) other;

        return ((this.getCleardate() == castOther.getCleardate()) || (this
                .getCleardate() != null && castOther.getCleardate() != null && this
                .getCleardate().equals(castOther.getCleardate())))
                && ((this.getRcktype() == castOther.getRcktype()) || (this
                .getRcktype() != null && castOther.getRcktype() != null && this
                .getRcktype().equals(castOther.getRcktype())))
                && (this.getRckorder() == castOther.getRckorder());
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result
                + (getCleardate() == null ? 0 : this.getCleardate().hashCode());
        result = 37 * result
                + (getRcktype() == null ? 0 : this.getRcktype().hashCode());
        result = 37 * result + this.getRckorder();
        return result;
    }

}
