package com.froad.beans;

// Generated 2014-8-4 9:40:50 by Hibernate Tools 3.4.0.CR1

import javax.persistence.*;

/**
 * Rckflow generated by hbm2java
 */
@Entity
@Table(name = "RCKFLOW")
public class Rckflow implements java.io.Serializable {

    private RckflowId id;
    private String beanid;
    private String initstate;
    private String alowchange;
    private String expcont;
    private String singleext;
    private String remark;
    private String msg;
    

    /**
	 * Getter method for property <tt>msg</tt>.
	 * 
	 * @return property value of msg
	 */
    @Column(name = "MSG")
	public String getMsg() {
		return msg;
	}

	/**
	 * Setter method for property <tt>msg</tt>.
	 * 
	 * @param msg value to be assigned to property msg
	 */
	public void setMsg(String msg) {
		this.msg = msg;
	}

	public Rckflow() {
    }

    public Rckflow(RckflowId id) {
        this.id = id;
    }

    public Rckflow(RckflowId id, String beanid, String initstate,
                   String alowchange, String expcont, String singleext, String remark,String msg) {
        this.id = id;
        this.beanid = beanid;
        this.initstate = initstate;
        this.alowchange = alowchange;
        this.expcont = expcont;
        this.singleext = singleext;
        this.remark = remark;
        this.msg = msg;
    }

    @EmbeddedId
    @AttributeOverrides({
            @AttributeOverride(name = "rcktype", column = @Column(name = "RCKTYPE", nullable = false, length = 20)),
            @AttributeOverride(name = "rckorder", column = @Column(name = "RCKORDER", nullable = false, precision = 9, scale = 0))})
    public RckflowId getId() {
        return this.id;
    }

    public void setId(RckflowId id) {
        this.id = id;
    }

    @Column(name = "BEANID")
    public String getBeanid() {
        return this.beanid;
    }

    public void setBeanid(String beanid) {
        this.beanid = beanid;
    }

    @Column(name = "INITSTATE", length = 5)
    public String getInitstate() {
        return this.initstate;
    }

    public void setInitstate(String initstate) {
        this.initstate = initstate;
    }

    @Column(name = "ALOWCHANGE", length = 5)
    public String getAlowchange() {
        return this.alowchange;
    }

    public void setAlowchange(String alowchange) {
        this.alowchange = alowchange;
    }

    @Column(name = "EXPCONT", length = 5)
    public String getExpcont() {
        return this.expcont;
    }

    public void setExpcont(String expcont) {
        this.expcont = expcont;
    }

    @Column(name = "SINGLEEXT", length = 5)
    public String getSingleext() {
        return this.singleext;
    }

    public void setSingleext(String singleext) {
        this.singleext = singleext;
    }

    @Column(name = "REMARK")
    public String getRemark() {
        return this.remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

}
